# Generated by Django 5.1.3 on 2024-11-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
            ],
        ),
    ]
